# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven


name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        java: [ '17' ]

    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java}}
          distribution: 'adopt'
          cache: maven
      
#       - name: cleaning old artifact data
#         run: ./mvnw clean
      
#       - name: building and storing artifact locally
#         run: ./mvnw -B package
        
      - name: creating settings.xml
        run: |
          echo "<settings xmlns='https://maven.apache.org/SETTINGS/1.0.0' \
            xmlns:xsi='https://www.w3.org/2001/XMLSchema-instance' \
            xsi:schemaLocation='https://maven.apache.org/SETTINGS/1.0.0 \
            http:s//maven.apache.org/xsd/settings-1.0.0.xsd'> \
              <servers> \
                <server> \
                  <id>DOB</id> \
                  <username>admin</username> \
                  <password>${{ secrets.NEXUSPASSWORD }}</password> \
                </server> \
              </servers> \
            </settings>" > ${{ github.workspace }}/settings.xml
      
      - name: Deploying to nexus
        run: ./mvnw deploy --settings ${{ github.workspace }}/settings.xml
